background            #2b3339
foreground            #d3c6aa
cursor                #d3c6aa
selection_background  #3a454a
selection_foreground  #d3c6aa

# Colors
color0  #4b565c
color8  #4b565c
color1  #e67e80
color9  #e67e80
color2  #a7c080
color10 #a7c080
color3  #dbbc7f
color11 #dbbc7f
color4  #7fbbb3
color12 #7fbbb3
color5  #d699b6
color13 #d699b6
color6  #83c092
color14 #83c092
color7  #d3c6aa
color15 #d3c6aa
