# SOURCE GENERATED COLORS
source = /home/zusqii/.config/matugen/generated/hyprlock.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%H")\n$(date +"%M")"
    color = $primary   
    font_size = 90
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = 0, 180
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = $primary     
    inner_color = $background
    font_color = $foreground
    fade_on_empty = false
    placeholder_text = <i>...</i>
    position = 0, -80
    halign = center
    valign = center
    fail_color = $error     
}
