background            #1a1c1e
foreground            #e2e2e6
cursor                #d0bcff
selection_background  #43474e
selection_foreground  #e2e2e6

# Colors
color0  #1a1c1e
color8  #43474e
color1  #ffb4ab
color9  #ffb4ab
color2  #77d8ff
color10 #77d8ff
color3  #d0bcff
color11 #d0bcff
color4  #d6e3ff
color12 #d6e3ff
color5  #f5c2e7
color13 #f5c2e7
color6  #94e2d5
color14 #94e2d5
color7  #c4c6d0
color15 #e2e2e6
